version: '2.4'

services:
  duckdns-letsencrypt:
    build: .
    restart: unless-stopped
    volumes:
      - ./certs:/etc/letsencrypt
    environment:
      # mandatory
      - "DUCKDNS_TOKEN=<your-duckdns-token>"
      - "DUCKDNS_DOMAIN=<your-duckdns-domain>"
      # optional
      # - "LETSENCRYPT_DOMAIN=<alternative-domain>"
      # - "LETSENCRYPT_EMAIL=<email-address>"
      # - "LETSENCRYPT_WILDCARD=false"
      # - "TESTING=false"

